{{- if .Values.gcs.credentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rctf.fullname" . }}-gcs-credentials
  labels:
    {{- include "rctf.labels" . | nindent 4 }}
type: Opaque
data:
  credentials-json: {{ .Values.gcs.credentials | mustToJson | b64enc | quote }}
{{- end -}}
