{{- if not .Values.postgres.passwordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rctf.fullname" . }}-postgres
  labels:
    {{- include "rctf.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-postgres-password: {{ required "postgres.password is required" .Values.postgres.password | b64enc | quote }}
{{- end }}
