{{- with .Values.email -}}
{{- with .sesProvider }}
{{- if empty .credentialsSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rctf.fullname" $ }}-ses
  labels:
    {{- include "rctf.labels" $ | nindent 4 }}
type: Opaque
data:
  aws-key-id: {{ required "email.sesProvider.awsKeyId is required" .awsKeyId | b64enc | quote }}
  aws-key-secret: {{ required "email.sesProvider.awsKeySecret is required" .awsKeySecret | b64enc | quote }}
  aws-region: {{ required "email.sesProvider.awsRegion is required" .awsRegion | b64enc | quote }}
{{- end -}}
{{- end -}}
{{- end -}}
