{{- with .Values.email -}}
{{- with .smtpProvider -}}
{{- if empty .urlSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rctf.fullname" $ }}-smtp
  labels:
    {{- include "rctf.labels" $ | nindent 4 }}
type: Opaque
data:
  url: {{ required "email.smtpProvider.url is required" .url | b64enc | quote }}
{{- end -}}
{{- end -}}
{{- end -}}
