apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rctf.fullname" . }}-token-key
  labels:
    {{- include "rctf.labels" . | nindent 4 }}
type: Opaque
data:
  token-key: {{ include "rctf.tokenKey" . | b64enc | quote }}
